In [3]:
# neural nw
import keras
import numpy as np

C:\Users\me389019\AppData\Local\Continuum\anaconda2\envs\nnseries\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
data_in=np.array([[0,0],[0,1],[1,0],[1,1]])
print(data_in)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [5]:
logic_and=np.array([[0],[0],[0],[1]])
print(logic_and)

[[0]
 [0]
 [0]
 [1]]


In [6]:
logic_or=np.array([[0],[1],[1],[1]])
print(logic_or)

[[0]
 [1]
 [1]
 [1]]


In [7]:
logic_xor=np.array([[0],[1],[1],[0]])
print(logic_xor)

[[0]
 [1]
 [1]
 [0]]


In [8]:
#keras tke all data at once
model=keras.models.Sequential(layers=[   # layer by layer # hidden layer # input layr # output layer
    # dense layer==fully connected graph
    keras.layers.Dense(input_dim=2,units=1),
    # sigmoid is good for binary outputs
    keras.layers.Activation(keras.activations.sigmoid)
])  

model.compile(optimizer=keras.optimizers.SGD(lr=0.5),loss="mse")


In [9]:
keras.backend.eval(model.weights[0])

array([[ 0.6710819],
       [-1.0844188]], dtype=float32)

In [10]:
model.fit(data_in,logic_or,epochs=1000,verbose=False)

In [11]:
model.predict(np.array([[1,0]]))

array([[0.9257875]], dtype=float32)