In [39]:
# SMSSpamCollection
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [40]:
df=pd.read_csv('SMSSpamCollection',sep='\t',names=['Status','Messages'])
print(df.head())
print(df.shape)
print("yohhhhooooooooooo we have a lot of data to classify spam or hamm  Is it a similar problem for email classification ?!")

  Status                                           Messages
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...
(5572, 2)
yohhhhooooooooooo we have a lot of data to classify spam or hamm  Is it a similar problem for email classification ?!


In [41]:
print("these are spams emails",len(df[df.Status=='spam']))
print("these are ham mails =",len(df[df.Status=='ham']))

these are spams emails 747
these are ham mails = 4825


In [42]:
# In this function we have replaced the spam amd ham by 0 and 1 as labels :::
df.loc[df["Status"]=='spam','Status']='1'
df.loc[df["Status"]=='ham','Status']='0'
print(df.head())

  Status                                           Messages
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...


In [43]:
df_y=df["Status"]
df_x=df["Messages"]
print("HERE IS YOUR DATASET \n",df_x)

HERE IS YOUR DATASET 
 0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
5       FreeMsg Hey there darling it's been 3 week's n...
6       Even my brother is not like to speak with me. ...
7       As per your request 'Melle Melle (Oru Minnamin...
8       WINNER!! As a valued network customer you have...
9       Had your mobile 11 months or more? U R entitle...
10      I'm gonna be home soon and i don't want to tal...
11      SIX chances to win CASH! From 100 to 20,000 po...
12      URGENT! You have won a 1 week FREE membership ...
13      I've been searching for the right words to tha...
14                    I HAVE A DATE ON SUNDAY WITH WILL!!
15      XXXMobileMovieClub: To use your credit, click ...
16                             Oh k...i'm watchin

In [44]:
cv=TfidfVectorizer(min_df=1,stop_words='english')

In [45]:
x_train,x_test,y_train,y_test=train_test_split(df_x,df_y,test_size=0.2,random_state=4)

In [46]:
x_trains=cv.fit_transform(["Hi how are you, you are the best ?","hey what's new today","lucky draw are"])
x_trains.toarray()


# this tfidf vectorizer helps u sto find the distribution of words in the whole docs

array([[0.70710678, 0.        , 0.        , 0.70710678, 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.57735027, 0.        , 0.        ,
        0.57735027, 0.57735027],
       [0.        , 0.70710678, 0.        , 0.        , 0.70710678,
        0.        , 0.        ]])

In [47]:
cv.inverse_transform(x_trains[0])

[array(['hi', 'best'], dtype='<U5')]

In [48]:
cv.get_feature_names()  # features are the words in our corpus

['best', 'draw', 'hey', 'hi', 'lucky', 'new', 'today']

In [49]:
cv.get_feature_names()  # features are the words in our corpus

['best', 'draw', 'hey', 'hi', 'lucky', 'new', 'today']

In [50]:
cv1 = TfidfVectorizer(min_df=1,stop_words='english')
# initialise a new count vectorizer above was just an example

In [51]:
x_traincv=cv1.fit_transform(x_train)
x_testcv=cv1.transform(x_test)

In [52]:
a=x_traincv.toarray()

In [53]:
a

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.19618715, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [54]:
a[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [55]:
cv1.inverse_transform(a[0])

[array(['checking', 'going', 'got', 'haha', 'lor', 'mails', 'online',
        'replying', 'sleeping', 'spys', 'wat'], dtype='<U27')]

In [56]:
mnb=MultinomialNB()

In [57]:
print(type(y_train))
y_train=y_train.astype('int') # they were may be str type we need to make them as int type
print(type(y_train))
mnb.fit(x_traincv,y_train)

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [58]:
pred=mnb.predict(x_testcv)    # what is diff. btwn fit and fit transform
print(pred)
print(type(pred))

[0 0 0 ... 0 0 1]
<class 'numpy.ndarray'>


In [59]:
actual = np.array(y_test)
actual= actual.astype('int')
print(actual)
print(type(actual))

[0 0 0 ... 0 0 1]
<class 'numpy.ndarray'>


In [60]:
print(accuracy_score(actual, pred)*100,"%")

95.7847533632287 %


In [61]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(actual, pred))

[[946   1]
 [ 46 122]]
